apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "5000" #These are the IO operations per second that the volume can support,
   # databases are faster when they can do more IO operations
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer